Feature/seedbox fix flexget
gandazgul/k8s-infrastructure pull request #47
Opened 2020-09-30 21:38 UTC by cybervoid

- added flexget to seedbox

2020-10-01 16:22 UTC, gandazgul requested changes

2020-10-01 16:22 UTC, gandazgul commented on helmfile.d/22-seedbox.yaml
> +      - values/seedbox.yaml.gotmpl
Rename my values file pls

2020-10-06 00:22 UTC, cybervoid commented on helmfile.d/22-seedbox.yaml
> +      - values/seedbox.yaml.gotmpl
@gandazgul done

2020-10-10 06:23 UTC, gandazgul approved these changes

2020-10-10 06:23 UTC, merged