[bitwarden-rs] - Added a release for Bitwarden RS
gandazgul/k8s-infrastructure pull request #63
Opened 2021-02-21 14:15 UTC by gandazgul

Signed-off-by: Carlos Ravelo <ravelo.carlos@gmail.com>

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] You documented the variables changed in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`) or helmfile name (e.g. `[ingress]`)

2021-02-25 02:24 UTC, cybervoid requested changes

2021-02-25 02:24 UTC, cybervoid commented on helmfile.d/27-bitwarden.yaml
> +      SMTP_USERNAME: { { requiredEnv "MAIL_TO" } }
@gandazgul fix the spacing here

2021-02-26 22:17 UTC, gandazgul commented on helmfile.d/27-bitwarden.yaml
> +      SMTP_USERNAME: { { requiredEnv "MAIL_TO" } }
done

2021-02-27 01:34 UTC, cybervoid approved these changes

2021-02-27 01:34 UTC, merged